apiVersion: v1
kind: Pod
metadata:
  name: slurm-client-dev
  namespace: slurm
  labels:
    name: sclient-dev
spec:
  nodeName: gs0
  containers:
  - image: registry.cn-shanghai.aliyuncs.com/pitech-docker-hub/slurm-client-dev:latest
    name: slurm-client-dev
    command: [ "/bin/bash", "-c" ]
    args:
    - service ssh restart;
      while true; do
      sleep 3600;
      done;
    ports:
    - containerPort: 22
    - containerPort: 8888
    volumeMounts:
    - mountPath: /etc/slurm-llnl
      name: slurm-config
    - mountPath: /opt/spack
      name: spack
    - mountPath: /mnt/hashfs
      name: data
    - mountPath: /mnt/users
      name: clusterfs
  volumes:
  - name: slurm-config
    hostPath:
      path: /mnt/deployment/picluster/src/k8s/slurm-conf
      type: Directory
  - name: spack
    hostPath:
      path: /mnt/spack
      type: Directory
  - name: data
    hostPath:
      path: /mnt/hashfs
      type: Directory
  - name: clusterfs
    hostPath:
      path: /mnt/users
      type: Directory
  imagePullSecrets:
  - name: aliyun
